version: '3.5'

services:
  remoteplay-build:
    build: ../
    container_name: 'remoteplay-build'
    volumes:
      - dist:/usr/src/app/dist

  remoteplay-web:
    image: nginx
    ports:
      - 80:80
    container_name: 'remoteplay-web'
    restart: unless-stopped
    environment:
      - API_PROXY_URL
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist: